apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wqul
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wqul
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wqul
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wqul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wqul
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jaoz-tenant/rhtap-demo-app/hacbs-test-project-wqul@sha256:9cad416d72790c92e99f0b31544d1baa1def5748b82df474189a98c8a2ca4c4c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
