apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-wqul
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jaoz-tenant/rhtap-demo-app/hacbs-test-project-wqul@sha256:9cad416d72790c92e99f0b31544d1baa1def5748b82df474189a98c8a2ca4c4c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
